# Site settings
title: content.supply
email: helpdesk@newatoms.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://content.supply" # the base hostname & protocol for your site

collections:
  homepage:
    output: false
  faq:
    output: false

defaults:
  -
    scope:
      path: en
    values:
      language: en
  -
    scope:
      path: homepage/en
    values:
      language: en
  -
    scope:
      path: faq/en
    values:
      language: en
  -
    scope:
      path: nl
    values:
      language: nl
  -
    scope:
      path: homepage/nl
    values:
      language: nl
  -
    scope:
      path: faq/nl
    values:
      language: nl

# Build settings
encoding: utf-8
markdown: kramdown
kramdown:
  input: GFM
highlighter: pygments

exclude: ["Gemfile", "Gemfile.lock", "bower_components"]
