# Site settings
title: content.supply
email: helpdesk@newatoms.com
baseurl: "" # the subpath of your site, e.g. /blog/

collections:
  homepage:
    output: false
  faq:
    output: false

defaults:
  -
    scope:
      path: en
    values:
      language: en
  -
    scope:
      path: _homepage/en
    values:
      language: en
  -
    scope:
      path: _faq/en
    values:
      language: en
  -
    scope:
      path: nl
    values:
      language: nl
  -
    scope:
      path: _homepage/nl
    values:
      language: nl
  -
    scope:
      path: _faq/nl
    values:
      language: nl

# Build settings
encoding: utf-8

exclude: ["Gemfile", "Gemfile.lock", "bower_components", "circle.yml"]
