# Site settings
title: content.supply
email: helpdesk@newatoms.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://content.supply" # the base hostname & protocol for your site

collections:
  homepage:
    output: false
  faq:
    output: false

# Build settings
encoding: utf-8
markdown: kramdown
kramdown:
  input: GFM
highlighter: pygments

exclude: ["Gemfile", "Gemfile.lock"]
